name: CI/CD

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'dev'
      - 'main'
    types: [closed]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  unit_test_and_build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    if: (!(github.event_name == 'pull_request' && github.event.pull_request.merged == false))
    steps:
      - uses: actions/checkout@v2
      - name: npm ci
        run: npm ci
      - name: npm run test
        run: npm run test
      - name: npm build
        run: npm run build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
