name: CI/CD

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'dev'
      - 'main'
    types: [closed]

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    if: (!(github.event_name == 'pull_request' && github.event.pull_request.merged == false))
    steps:
      - uses: actions/checkout@v2
      - name: npm ci
        run: npm ci
      - name: npm run test
        run: npm run test
      - name: npm build
        run: npm run build
      - name: GAE deploy
        run: gcloud app deploy app.yaml --project titanium-gadget-3215113
